baseurl = "https://yesterdog.github.io"
title = "amar chendra"
copyright = "Copyright &copy; 2017 - amar chendra"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "amar chendra"
    github = "yesterdog"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = ""
    instagram = ""

[params]
    tagline = ".."
